version: '2'

services:
  redis:
    image: redis

  app:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    logging:
      driver: syslog
      options:
        tag: '{{.Name}}'
    restart: on-failure
